[package]
name = "qorvex-repl"
version = "0.1.0"
edition = "2021"

[dependencies]
qorvex-core = { path = "../qorvex-core" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
base64 = "0.22"
