[package]
name = "qorvex-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
qorvex-core = { path = "../qorvex-core" }
tokio = { version = "1", features = ["full"] }
ratatui = "0.29"
crossterm = "0.29"
ratatui-image = "4"
image = "0.25"
base64 = "0.22"
